### ISSUE TITLE
Sklearn model

### ISSUE THREAD

**Issue by mwojcikowski** [mrkwjc/ffnet#1]
Hey,

I've lately constructed a wrapper for ffnet to make it compatible with sklearn models. https://github.com/oddt/oddt/blob/master/oddt/scoring/models/neuralnetwork.py I'd be happy to contribute if you find it worthy of merging.

**Comment by mrkwjc** [comment]
Hi!

Good idea :). This could be merged as `skffnet.py` file and class, and then imported as `from ffnet import skffnet`. However it would be nice to have at least a single test case for this and also better docstring. Could you draft a line of code which will use this class and actually compute something (for testing)?

Marek

**Comment by mwojcikowski** [comment]
Sure thing, for my own internal usage there were little urge to make proper docstrings. I'll create a PR.

**Comment by mrkwjc** [comment]
Closing old issue
